version: "3.9"
services:
db:
image: mysql:8.0
container_name: vericert-mysql
command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
environment:
MYSQL_DATABASE: ********
MYSQL_USER: ********
MYSQL_PASSWORD: *********
MYSQL_ROOT_PASSWORD: *******
volumes:
- db_data:/var/lib/mysql
ports:
- "3306:3306" # opzionale: esponi per collegarti da IDE
healthcheck:
test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "vericert", "-pvericert"]
interval: 5s
timeout: 3s
retries: 30


app:
build:
context: .
dockerfile: Dockerfile
container_name: vericert-app
environment:
SPRING_PROFILES_ACTIVE: docker
VERICERT_BASE_URL: http://localhost:8080
VERICERT_API_KEY_HEADER: X-API-KEY
VERICERT_API_KEY: change-me
volumes:
- certs_storage:/opt/vericert/storage/certificates
ports:
- "8080:8080"
depends_on:
db:
condition: service_healthy


volumes:
db_data:
certs_storage:
