vericert:
  master-key-b64: qTIHC6MLMfoxjQMRTwMvqz0awhBXwDQ7Eg2tSGQ7qmw=
  server:
    forward-headers-strategy: framework
  signing:
    alg: EdDSA
    kid: key-2025-10-30
    private-key-pem-path: keys/ed25519-private.pem
    public-key-pem-path: keys/ed25519-public.pem
  payments:
    currency: EUR
    success-url: https://app.vercert.org/checkout/success?session_id={CHECKOUT_SESSION_ID}
    cancel-url: https://app.vercert.org/checkout/cancel
    stripe:
      secret-key: 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
      webhook-secret: whsec_DgHQjJe1YG5TgsjVxEKP51JxSkZw0VKu
      publishable-key: pk_live_51QpNkvIX50JfMIoY1lyyItBWDYxDgzJJC2emFl8BKjpa8mc2ZzDsptEht4H9lLFiJrVCpP8tLyvhaTuBGNDEzeR00017AGlKAs
    paypal:
      client-id: AXWmEVZTOkqooLA4MEloFabS7_RDmqOYIFLaBEuBbEwU1dn0lJcdUIynhKEwyOV2bpRJxv0oCoIAm4Ax
      client-secret: EPGSWTvV6TEC2SOs559bPU3bkn7L_RRhy-7EkAykHNcgn44UPqrqih5o970G6TzFOfmyUOFJQemjD1gp
      mode: live
      success-url: https://app.vercert.org/paypal/success
      cancel-url: https://app.vercert.org/paypal/cancel
      apiBaseUrl: https://api-m.paypal.com
      webhookId: 9Y13644475209223A
    logging:
      level:
        root: INFO
        com.example.vericert: INFO
    spring:
      servlet:
        multipart:
          max-file-size: 15MB
          max-request-size: 15MB
